# Base de datos {.unlisted .unnumbered}

Se definen los años que se van a analizar a los índice de marginación 

```{r}
tablas <- c("2010", "2020")
```

**Se carga la base de datos**  


```{r}
for(i in tablas){
load(file = paste0(here::here(), "/Bases/IML_", i, ".RData")) 
}

##Se cambia el nombre de la columna año, para evitar problemas de puntuación
## Se cambia la variable año a factor
for(i in tablas){
assign(paste0("tabla_", i), get(paste0("tabla_", i)) %>% 
                             rename("ANIO" = "AÑO") %>%
                              filter(NOM_ENT != "Nacional") %>%
                               dplyr::mutate(ANIO = as.factor(.$ANIO)))
}
```

<div style="height:500px;overflow:auto;">
```{r, echo = FALSE}
require(gt)
tabla_2020 %>% 
 rename("AÑO" = "ANIO") %>%
  slice(1:25) %>%
    gt() %>%
     tab_header(title = "Indicadores simples de marginación",
                 subtitle = "2020") %>%
      fmt_number(columns = names(tabla_2020)[10:17], 
                  decimals = 2) %>%
       fmt_integer(columns = "POB_TOT", 
                    sep_mark = " ") %>%
        tab_options(heading.title.font.size = 12, 
                    heading.subtitle.font.size = 10,
                    table.font.names = 'montserrat',
                    table.font.size = 8,
                    data_row.padding = px(1)) %>%
         tab_style(style = list(cell_text(align = "left",
                                           weight = 'bold')),
                    locations = list(cells_title(groups = c("title")))) %>%
          tab_style(style = list(cell_text(align = "left")),
                     locations = list(cells_title(groups = c("subtitle")))) %>%
           cols_label(CVE_LOC = md("**CVE_LOC**"),
                      ENT = md("**ENT**"),
                      NOM_ENT = md("**NOM_ENT**"), 
                      MUN = md("**MUN**"), 
                      NOM_MUN = md("**NOM_MUN**"),
                      LOC = md("**LOC**"), 
                      NOM_LOC = md("**NOM_LOC**"), 
                      POB_TOT = md("**POB_TOT**"), 
                      AÑO = md("**AÑO**"), 
                      ANALF = md("**ANALF**"),
                      SBASC = md("**SBASC**"),
                      OVSDE = md("**OVSDE**"),
                      OVSEE = md("**OVSEE**"),
                      OVSAE = md("**OVSAE**"),
                      OVPT= md("**OVPT**"),
                      OVHAC = md("**OVHAC**"),
                      OVSREF = md("**OVSREF**")) %>%
         cols_width(starts_with("POB") ~ px(80), 
                    starts_with("NOM") ~ px(150), 
                    everything() ~ px(60)) %>%
            as_raw_html() 
```
</div>